### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ollivaan** [qzuw/DER-Tsoha#1]
-Dokumentaatio on tehty hyvin ja erittäin selkeäksi.
-Sivusto toimi hyvin eli tuotteiden luominen, poisto, esittely ja jne. toimi moitteetomasti.
-Yläpalkkiin (base.html) olisi kiva saada linkit joiden avulla voisi sivustolla surffailla, nyt jos meni etusivulle niin sivu "jämähti" siihen, mutta se on vain muodollisuus.
-koodissa eri html tiedostot kannattaisi jakaa paketteihin niin lukemisesta/järjestelystä tulisi helpompaa.
-Hyvät if kyselyt koodissa itse en ole vielä niihin päässytkään.
-Koodi näytti hyvin selkeältä ja  oli hyvin jäsennelty.
-Ihan ei auennut että mitä kayttaja.php all funktiossa $maara tekee

Kaikin puolin hyvännäköistä touhua !

terveisin: ollivaan
14:50 8.6.2016

**Comment by qzuw** [comment]
Kiitokset palautteesta. 
- base.html on nyt hieman muokattu, mutta se on edelleen kovin puutteellinen koska useimpia sivuja (ml etusivu) ja kirjautuminen ei ole vielä varsinaisesti toteutettu.
- Hieman epäselväksi jäänyt $maara oli lähinnä muistutuksena mahdollisesti toteutettavalle toiminnallisuudelle, joka on nyt toteutettu.
- Html-tiedostojen jakaminen erillisiin hakemistoihin on kyllä tehtävien asioiden listassa mutta saattaa jäädä edelleen myöhemmäksi

**Comment by qzuw** [comment]
Nyt html on jaoteltu soveltuviin alihakemistoihin. Yläpalkki on myös tässä välissä päivittynyt, joten tämän issuen voinee sulkea.

Viittaukset:
bd34e8250977cfe626f2adfd1bbf229fbdbc613c html-alihakemistoihin
681e63efd1618be43cc778263731b48b971bb4bf viimeisin päivitys yläpalkkiin
30c51c898ecf1764ecab152ef4f897911fe589d5 $maara
